# Generated by Django 4.2.6 on 2024-11-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('drink_type', models.CharField(choices=[('hot coffee', 'Hot Coffee'), ('cold coffee', 'Cold Coffee'), ('hot drink', 'Hot Drink'), ('cold drink', 'Cold Drink'), ('cakes', 'Cakes')], max_length=100)),
                ('specs', models.TextField(max_length=150)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
