# Generated by Django 5.2.8 on 2025-12-11 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_order_table_item_price_cents_orderitem_order_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='customizable',
            field=models.BooleanField(default=False, help_text='Allow customer to add custom notes/details (e.g., 70/30, extra sugar)'),
        ),
    ]
