# Generated by Django 5.2.8 on 2025-12-12 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_item_customizable'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Uncheck this if the item is temporarily unavailable (ناموجود)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='drink_type',
            field=models.CharField(choices=[('hot coffee', 'قهوه گرم'), ('cold coffee', 'قهوه سرد'), ('hot drink', 'نوشیدنی گرم'), ('cold drink', 'نوشیدنی سرد'), ('cakes', 'کیک و دسر')], max_length=100),
        ),
    ]
